pipeline {
    agent any
    environment {
        APP_NAME = "python-app"
    }
    stages {
        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }
        stage("Check out code") {
            steps {
                git branch: 'main', url: 'https://github.com/wodi12/python-app.git'
            }
        }
        stage("Update deployment image tag") {
            steps {
                sh """ 
                    cd manifests
                    cat deployment.yaml
                    sed -i 's/${APP_NAME}/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
                    cat deployment.yaml
                """
            }
        }
        stage("Deploy app") {
            steps {
                withKubeConfig(caCertificate: '', clusterName: "arn:aws:eks:${AWS_DEFAULT_REGION}:${ACCOUNT_ID}:cluster/python-app", contextName: '', credentialsId: 'k8s-cred', namespace: 'default', restrictKubeConfigAccess: false, serverUrl: "https://${CLUSTER_ID}.${AWS_DEFAULT_REGION}.eks.amazonaws.com") {
                    sh """
                        curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
                        chmod +x ./kubectl
                        mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
                        cd manifests
                        kubectl apply -f deployment.yaml
                    """
                }         
            }
        }
    }
    post {
        failure {
            slackSend(channel: '#alerts', color: "danger", message: "${BUILD_TAG} failed!")
        }
    }
}
